### ISSUE TITLE
Nested "features" raise error.

### ISSUE THREAD

**Issue by milkcocoa** [cavalle/steak#27]
After I updated Steak rc.1 to 1.0.0, my specs which uses nested feature like following raise error.

<pre>require File.expand_path(File.dirname(__FILE__) + '/../acceptance_helper')

feature "Users", %q{
  In order to ...
  As a ...
  I want to ...
} do

  background do
    setup_driver
  end

  feature "foo" do
    background do
      setup_user
    end

    scenario "bar" do
      true.should == true
    end
  end
end</pre>

Have nested features become not to be accepted?

Error is here.

<pre>RAILS_ROOT/spec/acceptance/api/users_spec.rb:13:in `block in <top (required)>': undefined method `feature' for #<Class:0x0000010322d9f0> (NoMethodError)</pre>

My environment is following.
- Ruby 1.9.2
- Rails 3.0.3
- RSpec 2.2.1
- Steak 1.0.0
